CS_2340_team19P2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns, set_language

from . import views

# Main urlpatterns for non-language-specific URLs (e.g., admin)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/auth/login/', permanent=False)),
    path('i18n/setlang/', set_language, name='set_language'),
]

# Language-specific URLs using i18n_patterns
urlpatterns += i18n_patterns(
    path('auth/', include('auth.urls')),  # Auth URLs with language prefix
    path('spotify/login/', views.spotify_login, name='spotify_login'),
    path('callback/', views.spotify_callback, name='spotify_callback'),
    path('wrapped/', include('wrapped.urls')),  # Wrapped URLs with language prefix
)

auth/urls.py
from django.urls import path
from . import views
app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

wrapped/urls.py
from django.urls import path, include
from . import views

app_name = 'wrapped'

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('', views.wrapped, name='wrapped'),
    path('loginWithSpotify/', views.user_spotify_login, name='user_spotify_login'),
    path('account/', views.account, name='account'),
    path('view-saved-wrap/<int:wrap_id>', views.view_saved_wrap, name='view_saved_wrap'),
    path('delete-wrap/<int:wrap_id>/', views.delete_wrap, name='delete_wrap'),
    path('view-saved-duo-wrap/<int:wrap_id>', views.view_saved_duo_wrap, name='view_saved_duo_wrap'),
    path('delete-duo-wrap/<int:wrap_id>/', views.delete_duo_wrap, name='delete_duo_wrap'),
    path('select/', views.select, name='select'),
    path('invite/', views.invite, name='invite'),
    path('spotify/login/', views.duo_spotify_login, name='duo_spotify_login'),
    path('duo/', views.duo, name='duo'),
    path('contactTheDevelopers', views.contact_developers, name='contact_developers'),
]

wrapped/models.py
from django.db import models
from django.contrib.auth.models import User


class SaveWrap(models.Model):
    """
    Model to store the user's Spotify wrapped data, including top artists,
    tracks, genres, and other statistics.

    Attributes:
        user (ForeignKey): The user associated with this wrap.
        user_data (JSONField): A JSON field to store general user data.
        top_artists (JSONField): A JSON field to store the top artists of the user.
        artist_songs (JSONField): A dictionary to store the user's songs for each artist.
        top_tracks (JSONField): A JSON field to store the user's top tracks.
        top_genres (JSONField): A list to store the user's top genres.
        genre_songs (JSONField): A dictionary to store the user's songs for each genre.
        average_valence (FloatField): A numerical value representing the user's average valence (mood).
        time_range (CharField): A string representing the time range of the wrap (e.g., '2023', 'last 6 months').
        created_at (DateTimeField): The date and time when the wrap was created (auto-generated).

    Methods:
        __str__: Returns a string representation of the SaveWrap instance, showing the user's username and time range.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Wrapped info
    user_data = models.JSONField()  # JSON
    top_artists = models.JSONField()  # JSON
    artist_songs = models.JSONField(default=dict)  # Store as dict
    top_tracks = models.JSONField()  # JSON
    top_genres = models.JSONField(default=list)  # Store as list
    genre_songs = models.JSONField(default=dict)  # Store as dict
    average_valence = models.FloatField()  # number
    time_range = models.CharField(max_length=50)  # string

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the SaveWrap instance.

        The string includes the username of the associated user and the time range
        of the wrap (e.g., '2024', 'last 6 months').

        :return str: The string representation of the SaveWrap instance.
        """
        return f"Saved Wrap for {self.user.username} ({self.time_range})"


class SaveDuoWrap(models.Model):
    """
    Model to store the duo wrapped data for two users, including compatibility
    scores, top tracks, and other statistics.

    Attributes:
        user (ForeignKey): The user associated with this duo wrap.
        user1_data (JSONField): A JSON field to store general data for the first user.
        user2_data (JSONField): A JSON field to store general data for the second user.
        compatibility (IntegerField): A numerical score representing the compatibility between the two users.
        valence_user1 (FloatField): The valence (mood) value for the first user.
        valence_user2 (FloatField): The valence (mood) value for the second user.
        top_tracks_user1 (JSONField): A JSON field to store the top tracks for the first user.
        top_tracks_user2 (JSONField): A JSON field to store the top tracks for the second user.
        interleaved_preview_urls (JSONField): A JSON field to store preview URLs for the interleaved duo tracks.
        created_at (DateTimeField): The date and time when the duo wrap was created (auto-generated).

    Methods:
        __str__: Returns a string representation of the SaveDuoWrap instance, showing the user's username.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Duo wrapped info
    user1_data = models.JSONField()  # JSON
    user2_data = models.JSONField()  # JSON
    compatibility = models.IntegerField()  # number
    valence_user1 = models.FloatField()  # number
    valence_user2 = models.FloatField()  # number
    top_tracks_user1 = models.JSONField()  # JSON
    top_tracks_user2 = models.JSONField()  # JSON
    interleaved_preview_urls = models.JSONField()  # JSON

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the SaveDuoWrap instance.

        The string includes the username of the associated user.

        :return str: The string representation of the SaveDuoWrap instance.
        """
        return f"Saved Duo Wrap for {self.user.username}"

wrapped/views.py
from collections import Counter
from statistics import mean

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from wrapped.models import SaveWrap, SaveDuoWrap
import requests

SPOTIFY_API_URL = "https://api.spotify.com/v1/me"
SPOTIFY_AUTH_URL = "https://accounts.spotify.com/authorize"
SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token"


@login_required
def user_spotify_login(request):
    """
    Renders the Spotify login page, requiring the user to be logged in.

    :param request: The HTTP request object.
    :return: HttpResponse: The rendered login page for Spotify authentication.
    """
    return render(request, 'loginWithSpotify.html', {})


@login_required
def wrapped(request):
    """
    Retrieves and displays the user's Spotify Wrapped data, saves it to the database,
    and renders the wrapped view. The data includes top artists, top tracks, top genres,
    and average valence over a specified time range.

    :param request: The HTTP request object, which should contain the access token and time range parameters.
    :return: HttpResponse: The rendered Wrapped page displaying the user's Spotify stats.
    """
    access_token = request.session.get('spotify_access_token')

    if not access_token:
        return redirect('spotify_login')

    time_range = request.GET.get('time_range', 'medium_term')

    user_data = get_spotify_user_info(access_token)
    top_artists_data, top_genres_data, top_tracks_data, average_valence, artist_songs, genre_songs = get_spotify_top_data(
        access_token, time_range)

    # Save the wrap data automatically upon loading
    saved_wrap = SaveWrap(
        user=request.user,
        user_data=user_data,
        top_artists=top_artists_data,
        artist_songs=artist_songs,
        top_tracks=top_tracks_data,
        top_genres=top_genres_data,
        genre_songs=genre_songs,
        average_valence=round(average_valence * 100),
        time_range=time_range
    )
    saved_wrap.save()

    return render(request, 'wrapped.html', {
        'user_data': user_data,
        'top_artists': top_artists_data,
        'artist_songs': artist_songs,
        'top_tracks': top_tracks_data,
        'top_genres': top_genres_data,
        'genre_songs': genre_songs,
        'average_valence': round(average_valence * 100),
        'selected_time_range': time_range
    })


@login_required
def view_saved_wrap(request, wrap_id):
    """
    Retrieves and displays a specific saved Spotify Wrapped data for the current user by ID.

    :param request: The HTTP request object.
    :param wrap_id: The ID of the saved Spotify Wrapped data to retrieve.
    :return: HttpResponse: The rendered Wrapped page displaying the saved Wrapped data.
    """
    # Get the specific saved wrap by ID
    wrap = get_object_or_404(SaveWrap, id=wrap_id, user=request.user)  # Ensure it's the current user's wrap

    # Get the time range from the request, default to the wrap's time range if not provided
    time_range = request.GET.get('time_range', wrap.time_range)

    # Prepare context to pass to the template
    context = {
        'user_data': wrap.user_data,
        'top_artists': wrap.top_artists,
        'artist_songs': wrap.artist_songs,
        'top_tracks': wrap.top_tracks,
        'top_genres': wrap.top_genres,
        'genre_songs': wrap.genre_songs,
        'average_valence': wrap.average_valence,
        'selected_time_range': time_range,
    }

    # Render the wrapped.html template with the context data
    return render(request, 'wrapped.html', context)


def get_spotify_user_info(access_token):
    """
    Fetches the current user's profile information from the Spotify API.

    :param access_token: The user's Spotify access token for authentication.
    :return: dict: The JSON response containing the user's profile information.
    """
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Content-Type': 'application/json'
    }
    response = requests.get(f"{SPOTIFY_API_URL}", headers=headers)
    return response.json()


def get_spotify_top_data(access_token, time_range):
    """
    Retrieves the user's top artists, top genres, top tracks, average valence,
    and associated songs for a given time range using the Spotify API.

    :param access_token: The user's Spotify access token for authentication.
    :param time_range: The time range to query for top artists, tracks, and genres (e.g., 'short_term', 'medium_term', 'long_term').
    :return: tuple: A tuple containing:
            - top_artists (list): The user's top artists.
            - genre_list (list): A list of the user's top genres.
            - top_tracks_data (dict): The user's top tracks.
            - average_valence (float): The average valence of the user's top tracks.
            - ordered_artist_songs (dict): A dictionary of top artists and their songs.
            - genre_songs (dict): A dictionary of genres and associated tracks.
    """
    # Top Artists
    url = "https://api.spotify.com/v1/me/top/artists"
    headers = {"Authorization": f"Bearer {access_token}"}
    params = {
        "limit": 50,
        "time_range": time_range
    }

    top_artists = requests.get(url, headers=headers, params=params)
    if top_artists.status_code != 200:
        return None, [], None, 0, {}, {}
    top_artists = top_artists.json()

    # Top Genres
    artists = top_artists.get("items", [])

    if artists is None or not artists:
        return top_artists, [], None, 0, {}, {}

    all_genres = []
    for artist in artists:
        genres = artist.get('genres', [])
        all_genres.extend([genre.title() for genre in genres])

    genre_counts = Counter(all_genres)
    sorted_genres = genre_counts.most_common()[0:5]
    genre_list = []
    for genre, count in sorted_genres:
        genre_list.append(genre)

    # Top Tracks
    top_tracks_url = "https://api.spotify.com/v1/me/top/tracks"
    headers = {"Authorization": f"Bearer {access_token}"}
    params = {
        "limit": 50,
        "time_range": time_range
    }

    top_tracks_data = requests.get(top_tracks_url, headers=headers, params=params)
    if top_tracks_data.status_code != 200:
        return top_artists, genre_list, None, 0, {}, {}
    top_tracks_data = top_tracks_data.json()

    # Average Valence
    # Get track IDs for fetching audio features
    track_ids = [track['id'] for track in top_tracks_data.get('items', []) if track.get('id')]

    # Fetch audio features for the top tracks
    audio_features_url = "https://api.spotify.com/v1/audio-features"
    params = {
        "ids": ','.join(track_ids)
    }

    audio_response = requests.get(audio_features_url, headers=headers, params=params)
    if audio_response.status_code != 200:
        return top_artists, genre_list, top_tracks_data, -1, {}, {}

    audio_features_data = audio_response.json()

    # Calculate average valence
    if audio_features_data and 'audio_features' in audio_features_data:
        valences = [feature['valence'] for feature in audio_features_data['audio_features'] if
                    feature['valence'] is not None]
        average_valence = sum(valences) / len(valences) if valences else 0
    else:
        average_valence = -1

    # Artist Tracks
    artist_songs = {}
    # Get the top 5 artists
    top_artists_list = top_artists.get('items', [])[:5]

    # Loop through top tracks to find songs by top artists
    for track in top_tracks_data.get('items', []):
        track_artists = {artist['name'] for artist in track['artists']}

        # Check if the track's artist is one of the top artists
        for artist in top_artists_list:
            artist_name = artist['name']
            if artist_name in track_artists and artist_name not in artist_songs:
                # If the artist has a track, assign the preview URL
                artist_songs[artist_name] = track.get('preview_url')
                break  # Exit loop after finding the first song for this artist

    # Check for any artists without songs and fetch their most popular song
    for artist in top_artists_list:
        artist_name = artist['name']

        # If the artist doesn't have a song yet, get their most popular song
        if artist_name not in artist_songs:
            popular_songs = get_artist_songs(access_token, artist['id'])
            if popular_songs:
                artist_songs[artist_name] = popular_songs[0].get('preview_url')

    # Create a list to preserve the order of top artists
    ordered_artist_songs = {artist['name']: artist_songs.get(artist['name']) for artist in top_artists_list}

    # Top Genre Songs
    genre_songs = {}
    added_songs = set()  # Set to keep track of added song URLs
    artist_genre_cache = {}  # Dictionary to cache artist genres

    # Function to get artist genres with caching
    def get_artist_genres_cached(artist_id):
        """
        Fetches the genres of a specific artist, caching the result for efficiency.

        :param artist_id: The Spotify ID of the artist.
        :return: A list of genres associated with the artist.
        """
        if artist_id in artist_genre_cache:
            return artist_genre_cache[artist_id]

        artist_url = f"https://api.spotify.com/v1/artists/{artist_id}"
        response = requests.get(artist_url, headers=headers)

        if response.status_code == 200:
            genres = response.json().get('genres', [])
            artist_genre_cache[artist_id] = genres  # Cache the result
            return genres
        return []

    # Loop through the list of genres
    for genre in genre_list:
        # Check each track in top_tracks
        for track in top_tracks_data.get('items', []):
            track_artists = track['artists']
            track_preview_url = track.get('preview_url')

templates/wrappedInvite.html
<!DOCTYPE html>
{% load i18n %}
<html data-wf-page="673628c658837b77b669c954" data-wf-site="671a91359e3597b13381098d"
      lang="{% get_current_language as language_code %}">
<head>
    <meta charset="utf-8">
    <title>{% trans "DuoWrapped Invite" %}</title>
    <meta content="{% trans 'DuoWrapped Invite' %}" property="og:title">
    <meta content="{% trans 'DuoWrapped Invite' %}" property="twitter:title">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
    {% load static %}
    <link rel="stylesheet" href="{% static 'normalize-invite.css' %}">
    <link rel="stylesheet" href="{% static 'webflow-invite.css' %}">
    <link rel="stylesheet" href="{% static 'spotify-wrapped-invite.webflow.css' %}">
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({google: {families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic", "Varela Round:400"]}});</script>
    <script type="text/javascript">
        /**
         * This script adds classes to the HTML document element based on the environment
         * (JavaScript support and touch capability), and includes links to favicon and Apple touch icon.
         *
         * 1. Adds a "js" class if JavaScript is supported.
         * 2. Adds a "touch" class if the device supports touch events.
         * 3. Sets favicon and Apple touch icon links in the HTML head.
         *
         * @function
         * @param {Window} o - The global `window` object.
         * @param {Document} c - The global `document` object.
         */
        !function (o, c) {
            // Get the root document element
            var n = c.documentElement,
                // Define a prefix for classes
                t = " w-mod-";

            // Add 'js' class to indicate JavaScript support
            n.className += t + "js";

            // Check if the device supports touch events (for touch devices)
            if ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) {
                // Add 'touch' class for touch-enabled devices
                n.className += t + "touch";
            }
        }(window, document);</script>
    <link href="../wrapped/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="../wrapped/static/images/webclip.png" rel="apple-touch-icon">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        /**
         * jQuery script for managing dropdown behavior.
         *
         * This script adds functionality to toggle a dropdown menu when clicking a button,
         * close the dropdown when clicking outside, and prevent closing the dropdown when
         * clicking inside it.
         */
        $(document).ready(function () {
            /**
             * Toggles the visibility of the dropdown when clicking the dropdown toggle button.
             *
             * This function listens for a click event on elements with the class `.w-dropdown-toggle`.
             * When clicked, it adds or removes the `open` class on the closest `.w-dropdown` element,
             * thus toggling its visibility.
             *
             * @function
             * @param {Event} event - The click event triggered when the toggle button is clicked.
             */
            $('.w-dropdown-toggle').click(function (event) {
                $(this).closest('.w-dropdown').toggleClass('open');
                event.stopPropagation();  // Prevents the click event from propagating to the document
            });

            /**
             * Closes any open dropdown when clicking anywhere outside of a dropdown.
             *
             * This function listens for click events on the document. If the click occurs outside
             * of any dropdown (i.e., the click target is not a descendant of `.w-dropdown`), it removes
             * the `open` class from all dropdowns, effectively closing them.
             *
             * @function
             * @param {Event} event - The click event triggered on the document.
             */
            $(document).click(function (event) {
                if (!$(event.target).closest('.w-dropdown').length) {
                    // If the click was outside the dropdown, close it
                    $('.w-dropdown').removeClass('open');
                }
            });

            /**
             * Prevents the dropdown from closing when clicking inside the dropdown itself.
             *
             * This function listens for click events on elements with the class `.w-dropdown`.
             * It stops the event from propagating to the document, preventing the dropdown from
             * being closed if the user clicks anywhere inside it.
             *
             * @function
             * @param {Event} event - The click event triggered inside the dropdown.
             */
            $('.w-dropdown').click(function (event) {
                event.stopPropagation();  // Prevents the event from reaching the document click handler
            });
        });
    </script>

    <!-- Custom CSS to show language dropdown -->
    <style>
        .w-dropdown-list {
            display: none;
        }

        .w-dropdown.open .w-dropdown-list {
            display: block;
        }
    </style>
</head>

<body style="background-image: url('../wrapped/static/images/8.png'), radial-gradient(circle, #8d167d, #fd9022);
    background-position: 50% 75%, 0 0;
    background-size: 101%, auto;">
<div class="navbar-logo-center">
    <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease"
         role="banner" class="navbar-logo-center-container shadow-three w-nav">
        <div class="navbar-wrapper-three">
            <ul role="list" class="nav-menu-block-2 w-list-unstyled">
                <li>
                    <a href="{% url 'wrapped:contact_developers' %}" class="nav-link-2">Contact Us</a>
                </li>
                <li>
                    <a href="{% url 'wrapped:invite' %}" class="nav-link-2">Invite</a>
                </li>
                <li>
                    <div data-hover="true" data-delay="0" class="nav-dropdown-2 w-dropdown">
                        <div class="nav-dropdown-toggle-2 w-dropdown-toggle">
                            <div class="nav-dropdown-icon-2 w-icon-dropdown-toggle"></div>
                            <div class="text-block-13">
                                {% get_current_language as language_code %}
                                {{ language_code|upper }}
                            </div>
                        </div>
                        <nav class="w-dropdown-list">
                            <!-- Language switch form -->
                            <form action="{% url 'set_language' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" name="language" value="en"
                                        class="nav-dropdown-link-2 w-dropdown-link">EN
                                </button>
                                <button type="submit" name="language" value="es"
                                        class="nav-dropdown-link-2 w-dropdown-link">ES
                                </button>
                                <button type="submit" name="language" value="fr"
                                        class="nav-dropdown-link-2 w-dropdown-link">FR
                                </button>
                            </form>
                        </nav>
                    </div>
                </li>
            </ul>
            <div class="text-block">
                <a href="{% url 'wrapped:select' %}" style="color: white; text-decoration: none;">[ Wrapped ]</a>
            </div>
            <section class="flex-block-2">
                 <a href="{% url 'wrapped:account' %}" class="button-5 w-button" style="border-radius: 100px; background-image: url('{{ user_data.images.0.url }}');"></a>
            </section>
            <div class="menu-button-2 w-nav-button"></div>
        </div>
        <div class="menu-button-2 w-nav-button"></div>
    </div>
</div>
<div class="div-block-19">
    <section class="section">
        <h2 id="w-node-_8335ce46-0b41-13a6-d23c-990e33264d5c-b669c954" class="heading-7">{% trans "DuoWrapped Invite" %}</h2>
        <div id="w-node-_244c6c47-7c76-9741-0b69-ff762cdb0312-b669c954" class="text-block-14"><strong
                class="bold-text-4">{% trans "Click here to link your friend’s Spotify!" %}</strong></div>
        <div id="w-node-aaf48690-e6eb-e50d-ed89-ddf08d7befb3-b669c954">
            <button type="button" onclick="window.location.href='{% url 'wrapped:duo_spotify_login' %}'"
                    id="w-node-b4ddf697-7443-f615-4b0d-ed29352bc7ce-b669c954" href="#" class="button-6 w-button">
                <strong>{% trans "Link Spotify" %}</strong></button>
        </div>
        <div style="display: flex; justify-content: center; align-items: center; text-align: center;">
            <p id="w-node-ad14d1a0-e8bd-de33-85b1-5a9ee54a3093-b669c954" class="paragraph">
                <strong class="bold-text-11">{% trans "Invite your friends to measure your compatibility from tracks, artists, and genres from DuoWrapped!" %}</strong>
            </p>
        </div>
    </section>
</div>
<script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=671a91359e3597b13381098d"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="{% static 'webflow-invite.js' %}" type="text/javascript"></script>
</body>
</html>